services:
  bot:
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - CONNECTION_URI=mongodb://mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    volumes:
      - mongodb:/data/db
    ports:
      - 127.0.0.1:27017:27017
  minio:
    # minioadmin:minioadmin
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    volumes:
      - minio:/data

volumes:
  mongodb:
  minio:
