services:
  bot:
    image: ghcr.io/khakers/openmodmail:develop
    restart: no
    build:
        context: .
        dockerfile: Dockerfile
        args:
          INCLUDE_SUPPORTUTILS: "true"
          INCLUDE_PIP: "true"
          PYTHON_VERSION: 3.13
#    env_file:
#      - .env
    environment:
      - CONNECTION_URI=mongodb://mongo
      - TOKEN=${DISCORD_BOT_TOKEN}
    depends_on:
      - mongo

volumes:
  mongodb:
